DEMO_PASSWORD = "password123"
PASSWORD_ROUNDS = 10

RESPONDERS = [
    {"name": "Jordan Blake", "email": "jordan.blake@northpeak.io", "role": "admin", "title": "Engineering Manager, SRE", "phone": "+1-415-555-0101"},
    {"name": "Priya Nair", "email": "priya.nair@northpeak.io", "role": "responder", "title": "Senior Site Reliability Engineer", "phone": "+1-415-555-0102"},
    {"name": "Marcus Webb", "email": "marcus.webb@northpeak.io", "role": "responder", "title": "Site Reliability Engineer", "phone": "+1-415-555-0103"},
    {"name": "Elena Cho", "email": "elena.cho@northpeak.io", "role": "responder", "title": "Backend Engineer, Payments", "phone": "+1-415-555-0104"},
    {"name": "Sam Okafor", "email": "sam.okafor@northpeak.io", "role": "responder", "title": "Backend Engineer, Platform", "phone": "+1-415-555-0105"},
    {"name": "Riley Tanaka", "email": "riley.tanaka@northpeak.io", "role": "responder", "title": "Mobile Platform Engineer", "phone": "+1-415-555-0106"},
    {"name": "Devon Ashworth", "email": "devon.ashworth@northpeak.io", "role": "responder", "title": "Security Engineer", "phone": "+1-415-555-0107"},
    {"name": "Naomi Fischer", "email": "naomi.fischer@northpeak.io", "role": "responder", "title": "Staff Engineer, Identity", "phone": "+1-415-555-0108"},
    {"name": "Theo Lindqvist", "email": "theo.lindqvist@northpeak.io", "role": "responder", "title": "DevOps Engineer", "phone": "+1-415-555-0109"},
]

SCHEDULES = [
    {
        "name": "SRE Primary On-Call",
        "description": "First responders for all customer-facing production incidents.",
        "time_zone": "America/Los_Angeles",
        "responder_emails": ["priya.nair@northpeak.io", "marcus.webb@northpeak.io", "jordan.blake@northpeak.io"],
        "rotation_type": "daily",
        "shift_length_hours": 24,
        "handoff_time": "09:00",
        "rotation_start_days_ago": 9,
    },
    {
        "name": "Backend Engineering On-Call",
        "description": "Secondary escalation for payments, checkout, and platform services.",
        "time_zone": "America/New_York",
        "responder_emails": ["elena.cho@northpeak.io", "sam.okafor@northpeak.io", "theo.lindqvist@northpeak.io"],
        "rotation_type": "weekly",
        "shift_length_hours": 168,
        "handoff_time": "10:00",
        "rotation_start_days_ago": 16,
    },
    {
        "name": "Identity & Security On-Call",
        "description": "Covers authentication, identity, and security-sensitive services.",
        "time_zone": "UTC",
        "responder_emails": ["naomi.fischer@northpeak.io", "devon.ashworth@northpeak.io"],
        "rotation_type": "weekly",
        "shift_length_hours": 168,
        "handoff_time": "09:00",
        "rotation_start_days_ago": 23,
    },
]

OVERRIDES = [
    {"schedule_name": "SRE Primary On-Call", "responder_email": "jordan.blake@northpeak.io", "start_days_from_now": 1, "duration_hours": 24, "reason": "Covering for Priya's dentist appointment."},
]

ESCALATION_POLICIES = [
    {
        "name": "Primary SRE Escalation",
        "description": "Standard three-tier escalation for high-urgency production incidents.",
        "levels": [
            {"target_type": "schedule", "target_name": "SRE Primary On-Call", "timeout_minutes": 10},
            {"target_type": "schedule", "target_name": "Backend Engineering On-Call", "timeout_minutes": 20},
            {"target_type": "responder", "target_email": "jordan.blake@northpeak.io", "timeout_minutes": 30},
        ],
    },
    {
        "name": "Identity & Security Escalation",
        "description": "Fast escalation path for authentication and security-sensitive services.",
        "levels": [
            {"target_type": "schedule", "target_name": "Identity & Security On-Call", "timeout_minutes": 5},
            {"target_type": "responder", "target_email": "naomi.fischer@northpeak.io", "timeout_minutes": 15},
        ],
    },
    {
        "name": "Low-Urgency Review",
        "description": "Relaxed single-tier policy for internal, non-customer-facing tools.",
        "levels": [
            {"target_type": "schedule", "target_name": "Backend Engineering On-Call", "timeout_minutes": 60},
        ],
    },
]

WORKFLOW_TEMPLATES = [
    {
        "name": "Database Outage Runbook",
        "steps": [
            {"title": "Confirm primary/replica health", "description": "Check replication lag and failover status in the database dashboard."},
            {"title": "Check recent deploys", "description": "Look for schema migrations or config changes in the last 2 hours."},
            {"title": "Notify stakeholders", "description": "Post a customer-facing status update if the outage affects checkout or payments."},
            {"title": "Confirm recovery", "description": "Verify write and read latency are back within SLO before resolving."},
        ],
    },
    {
        "name": "API Latency Spike Runbook",
        "steps": [
            {"title": "Check upstream dependencies", "description": "Review dependency health dashboards for degraded downstream services."},
            {"title": "Inspect autoscaling", "description": "Confirm the service scaled to handle current traffic; scale manually if needed."},
            {"title": "Review recent releases", "description": "Roll back the most recent deploy if it correlates with the spike."},
            {"title": "Confirm p99 latency recovered", "description": "Latency must be under SLO for 10 consecutive minutes before resolving."},
        ],
    },
    {
        "name": "Security Incident Runbook",
        "steps": [
            {"title": "Contain the exposure", "description": "Rotate any credentials or tokens that may have been exposed."},
            {"title": "Assess blast radius", "description": "Identify which accounts, services, or data may have been affected."},
            {"title": "Loop in security lead", "description": "Escalate to the security engineer on this policy before any public statement."},
            {"title": "Document timeline", "description": "Record every action taken for the post-incident review."},
            {"title": "Confirm remediation", "description": "Verify the vulnerability is patched and monitoring is in place."},
        ],
    },
]

SERVICES = [
    {
        "name": "Payments API",
        "description": "Card authorization, capture, and refund processing for all storefronts.",
        "owner_email": "elena.cho@northpeak.io",
        "escalation_policy": "Primary SRE Escalation",
        "workflow_template": "Database Outage Runbook",
        "default_urgency": "high",
    },
    {
        "name": "Checkout Web App",
        "description": "Customer-facing checkout flow served to web and mobile web traffic.",
        "owner_email": "sam.okafor@northpeak.io",
        "escalation_policy": "Primary SRE Escalation",
        "workflow_template": "API Latency Spike Runbook",
        "default_urgency": "high",
    },
    {
        "name": "Auth & Identity Service",
        "description": "Sign-in, session issuance, and multi-factor authentication for all products.",
        "owner_email": "naomi.fischer@northpeak.io",
        "escalation_policy": "Identity & Security Escalation",
        "workflow_template": "Security Incident Runbook",
        "default_urgency": "high",
    },
    {
        "name": "Customer Data Platform",
        "description": "Event pipeline and warehouse sync for customer analytics.",
        "owner_email": "sam.okafor@northpeak.io",
        "escalation_policy": "Primary SRE Escalation",
        "workflow_template": "Database Outage Runbook",
        "default_urgency": "low",
    },
    {
        "name": "Mobile Push Gateway",
        "description": "Push notification delivery for iOS and Android apps.",
        "owner_email": "riley.tanaka@northpeak.io",
        "escalation_policy": "Low-Urgency Review",
        "workflow_template": "API Latency Spike Runbook",
        "default_urgency": "low",
    },
    {
        "name": "Internal Admin Console",
        "description": "Back-office tools used by support and operations staff.",
        "owner_email": "theo.lindqvist@northpeak.io",
        "escalation_policy": "Low-Urgency Review",
        "workflow_template": None,
        "default_urgency": "low",
    },
]

# Incident scenarios seeded relative to "days ago" so the demo always looks current.
# status: triggered | acknowledged | resolved
INCIDENTS = [
    {
        "service": "Payments API",
        "title": "Elevated card authorization failures",
        "description": "Authorization success rate dropped below 92% for Visa transactions.",
        "urgency": "high",
        "status": "resolved",
        "days_ago": 42,
        "ack_minutes_after": 6,
        "resolve_minutes_after": 54,
        "assignee_email": "elena.cho@northpeak.io",
        "workflow": True,
        "workflow_done_steps": 4,
    },
    {
        "service": "Checkout Web App",
        "title": "Checkout page p99 latency above 4s",
        "description": "Frontend RUM shows checkout submission latency regressed after the 14:00 UTC deploy.",
        "urgency": "high",
        "status": "resolved",
        "days_ago": 35,
        "ack_minutes_after": 4,
        "resolve_minutes_after": 38,
        "assignee_email": "sam.okafor@northpeak.io",
        "workflow": True,
        "workflow_done_steps": 4,
    },
    {
        "service": "Auth & Identity Service",
        "title": "MFA challenge emails delayed",
        "description": "Email delivery provider reporting queue backlog for one-time codes.",
        "urgency": "low",
        "status": "resolved",
        "days_ago": 29,
        "ack_minutes_after": 12,
        "resolve_minutes_after": 96,
        "assignee_email": "naomi.fischer@northpeak.io",
        "workflow": False,
        "workflow_done_steps": 0,
    },
    {
        "service": "Customer Data Platform",
        "title": "Event pipeline backlog growing",
        "description": "Kafka consumer lag exceeds 30 minutes on the enrichment topic.",
        "urgency": "low",
        "status": "resolved",
        "days_ago": 24,
        "ack_minutes_after": 20,
        "resolve_minutes_after": 130,
        "assignee_email": "sam.okafor@northpeak.io",
        "workflow": True,
        "workflow_done_steps": 4,
    },
    {
        "service": "Payments API",
        "title": "Refund processing errors for EU accounts",
        "description": "Refunds failing with gateway timeout for accounts on the EU processor.",
        "urgency": "high",
        "status": "resolved",
        "days_ago": 18,
        "ack_minutes_after": 3,
        "resolve_minutes_after": 41,
        "assignee_email": "elena.cho@northpeak.io",
        "workflow": True,
        "workflow_done_steps": 4,
    },
    {
        "service": "Mobile Push Gateway",
        "title": "Android push delivery delayed",
        "description": "FCM delivery latency elevated for Android clients on carrier networks.",
        "urgency": "low",
        "status": "resolved",
        "days_ago": 13,
        "ack_minutes_after": 25,
        "resolve_minutes_after": 80,
        "assignee_email": "riley.tanaka@northpeak.io",
        "workflow": False,
        "workflow_done_steps": 0,
    },
    {
        "service": "Checkout Web App",
        "title": "Intermittent 502s from checkout gateway",
        "description": "Load balancer reporting sporadic upstream timeouts from the checkout service pods.",
        "urgency": "high",
        "status": "resolved",
        "days_ago": 7,
        "ack_minutes_after": 5,
        "resolve_minutes_after": 47,
        "assignee_email": "sam.okafor@northpeak.io",
        "workflow": True,
        "workflow_done_steps": 4,
    },
    {
        "service": "Internal Admin Console",
        "title": "Admin console login page returning 500",
        "description": "Support staff unable to reach the admin console login screen.",
        "urgency": "low",
        "status": "acknowledged",
        "days_ago": 2,
        "ack_minutes_after": 30,
        "resolve_minutes_after": None,
        "assignee_email": "theo.lindqvist@northpeak.io",
        "workflow": False,
        "workflow_done_steps": 0,
    },
    {
        "service": "Auth & Identity Service",
        "title": "Spike in failed login attempts from one IP range",
        "description": "Possible credential-stuffing attempt detected by the WAF against the login endpoint.",
        "urgency": "high",
        "status": "acknowledged",
        "days_ago": 1,
        "ack_minutes_after": 4,
        "resolve_minutes_after": None,
        "assignee_email": "devon.ashworth@northpeak.io",
        "workflow": True,
        "workflow_done_steps": 2,
    },
    {
        "service": "Payments API",
        "title": "Card authorization latency creeping up",
        "description": "P95 authorization latency trending toward the alert threshold over the last 30 minutes.",
        "urgency": "high",
        "status": "triggered",
        "days_ago": 0,
        "hours_ago": 2,
        "ack_minutes_after": None,
        "resolve_minutes_after": None,
        "assignee_email": None,
        "workflow": True,
        "workflow_done_steps": 1,
    },
    {
        "service": "Customer Data Platform",
        "title": "Warehouse sync job failed twice in a row",
        "description": "Nightly sync to the analytics warehouse has failed on its last two scheduled runs.",
        "urgency": "low",
        "status": "triggered",
        "days_ago": 0,
        "hours_ago": 5,
        "ack_minutes_after": None,
        "resolve_minutes_after": None,
        "assignee_email": None,
        "workflow": False,
        "workflow_done_steps": 0,
    },
]
