ROTATION_TYPES = ["daily", "weekly", "custom"]

MAX_NAME_LENGTH = 120
MAX_DESCRIPTION_LENGTH = 500
MIN_RESPONDERS = 1
MAX_RESPONDERS = 50
MIN_SHIFT_HOURS = 1
MAX_SHIFT_HOURS = 24 * 90
MAX_REASON_LENGTH = 200
HANDOFF_TIME_PATTERN = r"^([01]\d|2[0-3]):([0-5]\d)$"
UPCOMING_SHIFT_COUNT = 8
